profile: '' # set via github action
threshold:
  total: 90
exclude:
  paths:
    - main\.go$
    - ^client/jellyfin/models/
    - ^configuration/models/
    - ^server/models/ 
    - ^configuration/services/assets/
    - ^constants/