name: check test coverage

on:
    push:
        branches:
            - feat/*

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: 1.26.1

            - name: generate test coverage
              run: go test ./... -count=1 -coverprofile=./cover.out -covermode=atomic

            - name: check test coverage
              uses: vladopajic/go-test-coverage@v2
              with:
                  profile: cover.out
                  # badge will be generated and store on file system with `coverage.svg` name
                  badge-file-name: .github/badges/coverage.svg

            - name: Commit the badge (if it changed)
              run: |
                  if [[ `git status --porcelain` ]]; then
                    git config --global user.name 'github-actions[bot]'
                    git config --global user.email 'github-actions[bot]@users.noreply.github.com'
                    git add .github/badges/coverage.svg
                    git commit -m "bot: autogenerated test coverage badge"
                    git push
                  fi
